/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author gurua
 */
public class regi extends javax.swing.JFrame {

    /**
     * Creates new form regi
     */
    public regi() {
        initComponents();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collegedb","root","");
            JOptionPane.showMessageDialog(null,"Connected");        
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,"Not Connected");
        }
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        l5 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        c2 = new javax.swing.JComboBox<>();
        c3 = new javax.swing.JComboBox<>();
        l6 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        l7 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        l8 = new javax.swing.JLabel();
        c4 = new javax.swing.JComboBox<>();
        l9 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        l10 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        l11 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        l12 = new javax.swing.JLabel();
        p2 = new javax.swing.JPasswordField();
        cb1 = new javax.swing.JCheckBox();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("APR HOTEL");
        l1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRATION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Pristina", 1, 18))); // NOI18N
        jPanel2.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 373, 70));

        l2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("FIRST NAME");
        jPanel2.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 125, 167, 30));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 128, 391, 30));

        l3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("LAST NAME");
        jPanel2.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 176, 186, 27));
        jPanel2.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 176, 391, 27));

        l4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("GENDER");
        jPanel2.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 221, 186, 27));

        r1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("MALE");
        jPanel2.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 224, -1, -1));

        r2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("FEMALE");
        jPanel2.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 224, -1, -1));

        r3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("OTHERS");
        jPanel2.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 224, -1, -1));

        l5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setText("DOB");
        jPanel2.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 266, 186, 27));

        c1.setMaximumRowCount(10);
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--DATE--", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel2.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 271, 96, -1));

        c2.setMaximumRowCount(10);
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--MONTH--", "January", "Febraury", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));
        jPanel2.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 271, 120, -1));

        c3.setMaximumRowCount(10);
        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--YEAR--", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        jPanel2.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 271, -1, -1));

        l6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setText("AADHAR NUMBER");
        jPanel2.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 311, 186, 27));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel2.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 391, 27));

        l7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 255, 255));
        l7.setText("CITY");
        jPanel2.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 391, 186, 27));
        jPanel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 394, 391, 27));

        l8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 255, 255));
        l8.setText("STATE");
        jPanel2.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 445, 186, 27));

        c4.setMaximumRowCount(10);
        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--STATE--", "TAMIL NADU", "KERALA", "KARNATAKA", "ANDHRA PRADESH", "TELUNGANA", "DELHI", "MUMBAI", "GOA", "GUJARAT", "KASHMIR" }));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        jPanel2.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 448, 196, 27));

        l9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 255));
        l9.setText("PHONE NUMBER");
        jPanel2.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 506, 186, 27));
        jPanel2.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 498, 391, 27));

        l10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 255));
        l10.setText("MAIL ID");
        jPanel2.add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 579, 186, 27));
        jPanel2.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 582, 391, 27));

        l11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l11.setForeground(new java.awt.Color(255, 255, 255));
        l11.setText("PASSWORD");
        jPanel2.add(l11, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 661, 186, -1));
        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 661, 391, -1));

        l12.setBackground(new java.awt.Color(255, 255, 255));
        l12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        l12.setForeground(new java.awt.Color(255, 255, 255));
        l12.setText("CONFIRM PASSWORD");
        jPanel2.add(l12, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 731, -1, 27));

        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 731, 391, 27));

        cb1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cb1.setForeground(new java.awt.Color(255, 255, 255));
        cb1.setText("ACCEPT THE RULES AND CONDITIONS");
        jPanel2.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 799, 310, -1));

        b1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        b1.setText("REGISTER");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 820, 259, -1));

        b2.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        b2.setText("CLEAR");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 820, 164, 51));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("SHOW");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 660, 98, 22));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 391, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 690, 391, 22));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 16, 104, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 136, 210, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 586, 230, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 250, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 396, 330, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("If already have an account , login now");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 840, 230, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 496, 280, 30));

        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1650, 890));

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        jLabel6.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel9.setText("");
        jLabel2.setText("");
        jLabel3.setText("");
        jLabel8.setText("");
        int count=0;
        
        if(t1.getText().equals("")){
            jLabel6.setText("*Invalid user name");
           // jLabel6.setColor(red);
            jLabel6.setBackground(Color.red);
        }
         if(t2.getText().equals("")){
             jLabel4.setText("*Invalid last name");
         }
          if(t6.getText().equals("")){
              jLabel5.setText("*Invalid Email Id");
          }
          if(t4.getText().equals("")){
              jLabel8.setText("*Invalid city");
          }
          if(!cb1.isSelected())
          {
              JOptionPane.showMessageDialog(null,"Accept the rules and condition!!");
              count=1;
         }
        if(t5.getText().length()<10)
        {
            jLabel9.setText("*Invalid phone number");
            count=1;
        }
        else
        {
            int i=0;
            while(i!=t5.getText().length())
            {
                if(t5.getText().charAt(i)>=48&&t5.getText().charAt(i)<=57)
                {

                }
                else
                {
                    jLabel9.setText("*Invalid phone number");
                    count=1;
                    break;
                }
                i++;
            }
        }
        if(t3.getText().length()<12)
        {
            jLabel2.setText("*Invalid aadhar number");
            count=1;
        }
        else
        {
            int i=0;
            while(i!=t3.getText().length())
            {
                if(t3.getText().charAt(i)>=48&&t3.getText().charAt(i)<=57)
                {
                       
                }
                else
                {
                    jLabel2.setText("*Invalid aadhar number");
                    count=1;
                    break;
                }
                i++;
            }
        }
        int j=0;
        int count1=0,count2=0,count3=0;
        String m=p1.getText();
        while(p1.getText().length()!=j)
        {

            if(m.charAt(j)>=48&&m.charAt(j)<=57)
            {
                count1=1;
            }
            if(m.charAt(j)>='a'&&m.charAt(j)<='z')
            {
                count2=1;
            }
            if(m.charAt(j)>='A'&&m.charAt(j)<='Z')
            {
                count3=1;
            }
            j++;
        }
        int flag=0;
        if(count1==1&&count2==1&&count3==1)
        {
            flag=1;
        }
        else
        {
            flag=0;
            jLabel3.setText("*Invalid password");
           
        }
        if(t1.getText().equals("")==true || t2.getText().equals("")==true || t3.getText().equals("")==true || t4.getText().equals("")==true || t5.getText().equals("")==true || t6.getText().equals("")==true )
        {
            count=1;
        }
         if(count==0&&flag==1){

           try 
           {
           // Class.forName("com.mysql.jdbc.Driver");
                
                jLabel2.setText("");
                jLabel3.setText("");
                jLabel9.setText("");
                jLabel5.setText("");
                jLabel4.setText("");
                jLabel8.setText("");
                String sample;
                if(r1.isSelected())
                {
                    sample="male";
                }
                else if(r2.isSelected())
                {
                    sample="female";
                }
                else if(r3.isSelected())
                {
                    sample="others";
                }
                else
                sample="not selected";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
            Statement stmt = con.createStatement();       
            String q1 = "insert into registration values('" +t1.getText()+"','"+t2.getText()+"','"+sample+"','"+c1.getItemAt(c1.getSelectedIndex())+"-"+c2.getItemAt(c2.getSelectedIndex())+"-"+c3.getItemAt(c3.getSelectedIndex())+"','"+t3.getText()+"','"+t4.getText()+"','"+c4.getItemAt(c4.getSelectedIndex())+"','"+t5.getText()+"','"
                +t6.getText()+"','"+p1.getText()+"')";
            stmt.executeUpdate(q1);
            JOptionPane.showMessageDialog(null,"Inserted");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
         }
         count=0;
    }//GEN-LAST:event_b1ActionPerformed
    
    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        p1.setText("");
        p2.setText("");
        c1.setSelectedIndex(0);
        c2.setSelectedIndex(0);
        c3.setSelectedIndex(0);
        c4.setSelectedIndex(0);  
        r1.setSelected(false);
        r2.setSelected(false);
        r3.setSelected(false);
    }//GEN-LAST:event_b2ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
       {
           p1.setEchoChar((char)0);
       }
       else
       {
           p1.setEchoChar('*');
           
       }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new Loginform().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JComboBox<String> c4;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
